### ISSUE TITLE
Main Queue Setup

### ISSUE THREAD

**Issue by sdossick** [huextrat/react-native-screenshot-aware#11]
Getting a yellow box warning "Module ScreenshotAware requires main queue setup since it overrides 'init' but doesn't implement 'requiresMainQueueSetup'".  This is only an issue for a future RN release so we've just added it to our LogBox.ignoreLogs, but it would be nice to fix.

**Comment by huextrat** [comment]
Hi @sdossick, following PR should fix it https://github.com/huextrat/react-native-screenshot-aware/pull/12
