### ISSUE TITLE
Android version supports 

### ISSUE THREAD

**Issue by omar-bear** [huextrat/react-native-screenshot-aware#27]
small question please: This library support only android 14 ? which mean if user has Android 13 this will not work ?

**Comment by huextrat** [comment]
@omar-bear As mentioned here https://github.com/huextrat/react-native-screenshot-aware#android, this library will notify you of screenshots only from Android 14.

Screenshots on versions below Android 14 are not captured by this library.

The main reason is that Android implemented the screenshot detection API in Android 14.

There are solutions, however, for capturing screenshots on Android 13 and below, but these are devious means that require the user to authorize access to their files.

**Comment by omar-bear** [comment]
Thank you so much, @huextrat. So if I want to support users on versions below 14, I have to add permission to access their files, right? This is considered a dangerous permission, and it will prompt users for their approval?

**Comment by huextrat** [comment]
If you want to detect screenshot below Android 14 you will have to use another library or do your own module, this one won't let you do it
